### ISSUE TITLE
Implementing bot function

### ISSUE THREAD

**Issue by yuhattor** [Azure/aca-preview#31]
TBD: Need to research how to realize this

![image](https://user-images.githubusercontent.com/15963767/189882960-11b0bed8-5626-41dd-831c-a1bfb028c584.png)

**Comment by horihiro** [comment]
Related to this feature, I want to clearify the range of the responsibility / scope of this action.
Point me out, if I misunderstand.

Will this feature be implemeted in this action?

I thought that users can build their workflow by using another action like https://github.com/peter-evans/create-or-update-comment, like the following example, if they want this featuer in the workflow at their own risk.

```yml
jobs:
  build-and-deploy:
    steps:
      - name: add new revision to ACA
        uses: Azure/aca-depoloy@v1
        id: aca_new_revision
        with: 
        # some parameters for aca-deploy

      - name: add new comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
          # comment body using ${{ steps.aca_new_revision,outputs.revisionUrl_or_something }}
```

**Comment by yuhattor** [comment]
Thanks for your comments.
What we need to do here is. 
We only need to use one aca-deploy action like below to make this happen.

```
jobs:
  build-and-deploy:
    steps:
      - name: add new revision to ACA
        uses: Azure/aca-depoloy@v1
        id: aca_new_revision
        with: 
        # some parameters for aca-deploy
```

In other words, I think it would be ideal to also include code in the implementation of the aca-deploy action that would update the comments, using the following code as a reference.
https://github.com/peter-evans/create-or-update-comment/blob/main/index.js
